### ISSUE TITLE
Forge server crash on startup: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by grothedev** [Minecraft-LightLand/L2Artifacts#1]
MC version: 1.19.2
Forge version: 43.1.1
added L2Artifacts and L2Library to a forge server (curios already present). 
[server log with stack trace](https://hastebin.com/raw/niluxowisa)

seems weird that it would be doing anything relating to GUI

**Comment by lcy0x1** [comment]
Should be fixed in 1.4.0
