### ISSUE TITLE
crash with neoforge 1.21.1 .66

### ISSUE THREAD

**Issue by VaporeonScripts** [Minecraft-LightLand/L2Artifacts#11]
https://mclo.gs/3bFo4i6

**Comment by lcy0x1** [comment]
I forgot to clean up L2Backpack dependency from this mod. The artifact swap takes L2Backpack and I will make sure it runs without L2Backpack in next version

**Comment by VaporeonScripts** [comment]
alright,ty

**Comment by lcy0x1** [comment]
fixed in 3.0.0+3
