### ISSUE TITLE
cant put artifacts into body and bracelet curios slots

### ISSUE THREAD

**Issue by krjencik** [Minecraft-LightLand/L2Artifacts#5]
head , necklace and belt works 
Minecraft 1.19.4, Forge 45.0.59

**Comment by lcy0x1** [comment]
They are supposed to have their own curio slots in 1.19.4. Just fixed the bug that they are assigned into the old slots. Try if 2.2.1 works.

Sorry for the bug.

**Comment by krjencik** [comment]
yea it works now. Ty a lot. :) 
good Idea of making their own slots I think ;)
