### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Vadewolf** [Minecraft-LightLand/L2Artifacts#7]
[crash-2023-12-24_22.24.58-client.txt](https://github.com/Minecraft-LightLand/L2Artifacts/files/13763890/crash-2023-12-24_22.24.58-client.txt)

**Comment by Vadewolf** [comment]
[crash-2023-12-25_20.07.08-client.txt](https://github.com/Minecraft-LightLand/L2Artifacts/files/13767997/crash-2023-12-25_20.07.08-client.txt)

**Comment by lcy0x1** [comment]
This is Iris - Ars Nouveau - Geckolib issue when rendering armor
